use_frameworks!
install! 'cocoapods', :deterministic_uuids => false

platform :ios, '13.0'

target 'JbCompass_Example' do
  pod 'JbCompass', :path => '../'

  target 'JbCompass_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 10.0.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 9.4.0'
  end
end
